---
name: publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  publish:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        package:
          - handle-abort
          - handle-aws-x-ray
          - handle-errors
          - handle-request
          - handle-timer

    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          name: dist

      - uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: install
        run: npm ci

      - name: publish
        run: npm publish --access public --provenance
