---
name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      matrix:
        package:
          - handle-abort
          - handle-aws-x-ray
          - handle-errors
          - handle-request
          - handle-timer

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: yarn
        run: yarn install --frozen-lockfile

      - name: build ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: yarn build

      - name: publish ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
